.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2020 Cézar Augusto de Campos <cezargaiteiro@protonmail.com>,
.TH MOLOTOV "1" "November 2020" "Molotov 0.6.10" "User Commands"
.\" Please adjust this date whenever revising the manpage.

.SH NAME
molotov \- Create a bootable media from a Windows® 10 iso image.
.SH SYNOPSIS
.IP
molotov \fB\-i\fR <iso\-image> \fB\-d\fR <block-device> [OPTIONS]
.SH OPTIONS
This program follows the usual GNU command line syntax, with long
options starting with two dashes (--). A summary of options is included below.
.TP
\fB\-i\fR, \fB\-\-iso\-image\fR FILE
Iso image to be used in the media creation
.TP
\fB\-d\fR, \fB\-\-device\fR DEVICE
Device where the image must be burnt, it must be a block device
.TP
\fB\-h\fR, \fB\-\-help\fR
Display the help message
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Turn on verbose output
.TP
\fB\-V\fR, \fB\-\-version\fR
Print molotov version and exit
.TP
\fB\-u\fR, \fB\-\-uefi\fR
Make an uefi\-bootable media
(default is legacy)
.PP
Mandatory or optional arguments to long options are also mandatory
or optional for any corresponding short options.
.SH "EXIT CODES"
This program has custom exit codes for debugging purposes, a summary is listed bellow.
.TP
\fB0\fR
It means that the script ran successfully
.TP
\fB64\fR
Unknown parameter
.TP
\fB65\fR
Missing required arguments, it happens when the user omits either the -i or -d flag
.TP
\fB66\fR
Iso image not found, when the user passes as argument a non-existent ISO image
.TP
\fB67\fR
Block device not found, when the user passes as argument a non-existent device
.TP
\fB68\fR
Insufficient permissions, it happens when the program is not run as root
.SH "REPORTING BUGS"
Report bugs to <https://github.com/cizordj/molotov>
.SH COPYRIGHT
Copyright \(co Cézar Augusto de Campos

License: MIT
